---
latitude: 40.7650395
longitude: -73.9833072
map_zoom: 13
name: The Manhattan Club - Ownership
email: support@traveltripper.com
phone_number: 123-123-1234
address:
  street1: 200 W 56th St.
  state: NY
  city: New York
  zip_code: 10019
default_currency: USD
default_timezone: America/New_York
_hotel_id: NYCTMC
_portal_id: manhattanclub
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.3
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  logo_secondary:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
    latitude:
      type: float
    longitude:
      type: float
logo:
  name: The Manhattan Club
  content_type: image/png
  date_added: 2019-03-08-040921
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1552036161/cqsuwlrukzbneaj9d9jw.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1552036161/cqsuwlrukzbneaj9d9jw.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1552036161/cqsuwlrukzbneaj9d9jw.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1552036161/cqsuwlrukzbneaj9d9jw.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1552036161/cqsuwlrukzbneaj9d9jw.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1552036161/cqsuwlrukzbneaj9d9jw.png"
  width: 158
  height: 116
  format: png
  url: "//res.cloudinary.com/traveltripperweb/image/upload/v1552036161/cqsuwlrukzbneaj9d9jw.png"
  resource_type: image
  size: 8842
  path: "//res.cloudinary.com/traveltripperweb/image/upload/v1552036161/cqsuwlrukzbneaj9d9jw.png"
  file_size:
  alt: The Manhattan Club
  caption: ''
  description: ''
logo_secondary:
  name: The Manhattan Club
  content_type: image/png
  date_added: 2019-03-12-035113
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1552377073/phxlf0kqc5tfzpmetwts.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1552377073/phxlf0kqc5tfzpmetwts.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1552377073/phxlf0kqc5tfzpmetwts.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1552377073/phxlf0kqc5tfzpmetwts.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1552377073/phxlf0kqc5tfzpmetwts.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1552377073/phxlf0kqc5tfzpmetwts.png"
  width: 158
  height: 17
  format: png
  url: "//res.cloudinary.com/traveltripperweb/image/upload/v1552377073/phxlf0kqc5tfzpmetwts.png"
  resource_type: image
  size: 3215
  path: "//res.cloudinary.com/traveltripperweb/image/upload/v1552377073/phxlf0kqc5tfzpmetwts.png"
  file_size:
  alt: The Manhattan Club
  caption: ''
  description: ''
phone: 888-692-2121
get_directions_url: https://goo.gl/maps/7zfH8H5tnUw
