---
latitude: 37.806699
longitude: -122.4172393
map_zoom: 13
name: Hotel Caza
email: reservations@hotelcaza.com
phone_number: 888-976-3558
address:
  street1: '1300 Columbus Avenue'
  state: 'San Francisco'
  city: 'California'
  zip_code: '94133'
default_currency: USD
default_timezone: America/New_York
_hotel_id: SFOCZA
_portal_id: hotelcaza
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.2
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
logo:
  name: Hotel Caza
  content_type: image/png
  date_added: 2019-03-18-074813
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1552909693/dk5czpj2v50duqoh6pi7.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1552909693/dk5czpj2v50duqoh6pi7.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1552909693/dk5czpj2v50duqoh6pi7.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1552909693/dk5czpj2v50duqoh6pi7.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1552909693/dk5czpj2v50duqoh6pi7.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1552909693/dk5czpj2v50duqoh6pi7.png"
  width: 316
  height: 152
  format: png
  url: "//res.cloudinary.com/traveltripperweb/image/upload/v1552909693/dk5czpj2v50duqoh6pi7.png"
  resource_type: image
  size: 13801
  path: "//res.cloudinary.com/traveltripperweb/image/upload/v1552909693/dk5czpj2v50duqoh6pi7.png"
  file_size:
  alt: Hotel Caza
  caption: ''
  description: ''
phone: '0861 444 435'
get_directions_url: https://goo.gl/maps/NUabYKekc2npwreq5
